Review
scaleracademy/sclr.ac-backend pull request #5
Opened 2021-06-14 19:31 UTC by AVS18

Added a code function that checks whether a URL shortcode has been already created. If yes then Rerun the same loop to create a new shortcode.

 let check = getShortCodeDetails(shortCode)    if(check!==undefined){        return await createRandomShortCode(longUrl);    }

2021-06-15 14:28 UTC, championswimmer commented
Please name the pull request as `Fixes <xyz> issue`, or `Adds <xyz> feature` to be more descriptive :)

2021-06-15 14:30 UTC, championswimmer requested changes

2021-06-15 14:30 UTC, championswimmer commented on src/controllers/shortcode.controller.ts
> +    if(check!==undefined){
if (!check) is a better check as that checks for `false`, `null`, `undefined` all 3 cases. 

Also your if-condition is opposite. We should recurse only if it **IS** undefined, not the other way around.

2021-06-15 20:34 UTC, AVS18 commented on src/controllers/shortcode.controller.ts
> +    if(check!==undefined){
if(!check) I will add. Can you elaborate more over the second one that recurse only if it IS undefined.
as of now, I did check for the shortcode if exist and if it is not undefined that means the shortcode already exist in the database hence you need to again recall to generate a new code.

2021-06-16 17:37 UTC, championswimmer commented on src/controllers/shortcode.controller.ts
> +    if(check!==undefined){
ah ok my bad. logic was correct in yours. 

btw you need to await the response of  `getShortCodeDetails(shortCode)`

2021-06-18 16:34 UTC, closed without merging

2021-06-18 16:36 UTC, AVS18 commented on src/controllers/shortcode.controller.ts
> +    if(check!==undefined){
Hi, i missed some conversation here. Is this still unresolved.